blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^$', views.homeview, name='home'),
    url(r'^feeds/$', views.ArticleListView.as_view(), name='feeds'),
    url(r'^feeds/category/version/$', views.VersionListView.as_view(), name='versionlist'),
     url(r'^feeds/category/tech/$', views.TechListView.as_view(), name='Techlist'),
      url(r'^feeds/category/review/$', views.ReviewListView.as_view(), name='Reviewlist'),
    url(r'^feeds/category/music&entertainment/$', views.MusicListView.as_view(), name='Musiclist'),
     url(r'^feeds/category/lifestyle/$', views.LifestyleListView.as_view(), name='Lifestylelist'),   
    url(r'^feeds/tags/(?P<tag>\w+)$',views.tagpage ,name='tagepage'),
    url(r'^archive/$', views.ArchiveView.as_view(), name="archive"),
    url(r'search/$', views.search,name = 'search'),
    url(r'^feeds/(?P<slug>\S+)$', views.ArticleDetailView.as_view(), name='detail'),
   
]

usersubmit/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'createpost/$', views.postview,name = 'createpost'),
     url(r'postfeeds/$', views.PostListView.as_view(),name = 'postfeeds'),
     url(r'^post_edit/(?P<slug>\S+)$', views.post_edit, name='postedit'),
     url(r'^remove/(?P<slug>\S+)/$', views.post_remove, name='post_remove'),
     url(r'^post/(?P<slug>\S+)$', views.ArticleDetailView.as_view(), name='postdetail'),
     url(r'^like/$', views.post_like, name='like'),
     
]

version/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls',)),
    url(r'^', include('blog.urls',  namespace='blog')),
    url(r'^', include('usersubmit.urls',  namespace='usersubmit')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersubmit/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models.signals import pre_save 
from django.contrib.auth.models import User
from django.utils.text import slugify
from taggit.managers import TaggableManager
from sorl.thumbnail import ImageField


# Create your models here.

class Post(models.Model):
    CATEGORY_CHOICES = (
    ('Tech', 'Tech'),    
    ('Review', 'Review'),
    ('Version', 'Version'),
    ('Music', 'Music'),
    ('Fashion', 'Fashion'),
    ('Culture', 'Culture'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True,default=None)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    tags = TaggableManager()
    created = models.DateField(auto_now_add = True)
    author = models.ForeignKey(User, related_name='uploaded_by')
    published = models.BooleanField(default=True)
    allow_comments = models.BooleanField('allow comments', default=True)
    favorited_by_version = models.BooleanField(default = False)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='post_liked',
                                        blank=True)

    class Meta:
        verbose_name_plural = ('articles')
        ordering = ['-created']

    def __str__(self):
        return self.title

    

    def get_absolute_url(self):
        return reverse('usersubmit:postdetail', kwargs={'slug': self.slug})

    def get_first_image(self):
        return self.images_set.all()[0]

def create_slug(instance,new_slug=None):
    slug= slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs= Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists
    if exists():
        new_slug="%s-%s" %(slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug   

def pre_save_post_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_receiver,sender=Post)        
  
        

def get_image_filename(instance, filename):
    title = instance.article.title
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename)  



class Images(models.Model):
    article = models.ForeignKey(Post)
    image = ImageField(upload_to=get_image_filename,
                              verbose_name='Image', )
    body = models.TextField(max_length=500)    
    
    class Meta:
        verbose_name_plural = ('images')

       
    def __unicode__(self):
        return self.article                         

usersubmit/forms.py
from django import forms


from .models import Post,Images

class PostForm(forms.ModelForm):
    category = forms.ChoiceField(widget=forms.Select,choices=Post.CATEGORY_CHOICES)
    class Meta:
        model = Post
        fields = ('title','category','tags' )
        widgets={"category":forms.Select(attrs={'class':'input-field'}), }  

class ImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ('image','body', )

ImageFormset= forms.modelformset_factory(
    Images,
    form=ImageForm,
)       

ImageInlineFormSet = forms.inlineformset_factory(
    Post,
    Images,
    extra=0,
    fields = ('image','body', ),
    formset=ImageFormset,
    min_num=1,
)

usersubmit/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import DetailView
from el_pagination.views import AjaxListView
from . import forms
from .models import *
from common.decorators import ajax_required
from actions.utils import create_action
# Create your views here.

class PostListView(AjaxListView):
    context_object_name = "post"
    template_name = "usersubmit/post_grid.html"
    page_template='usersubmit/post_ajax.html'

    def get_queryset(self):
        return Post.objects.all()





class ArticleDetailView(DetailView):
    model = Post    


@login_required
def postview(request):
    form = forms.PostForm()
    formset = forms.ImageInlineFormSet(queryset=Images.objects.none())

    if request.method == 'POST':
        form = forms.PostForm(request.POST)
        formset=forms.ImageInlineFormSet(request.POST,request.FILES,queryset=Images.objects.none())
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author  = request.user
            post.save()
            form.save_m2m()
            images = formset.save(commit=False)
            for image in images:
                image.article = post
                image.save()
            create_action(request.user, 'Posted new', post)    
            messages.success(request,'Post added.')
            return HttpResponseRedirect('/postfeeds')
    return render(request,'usersubmit/post_create.html',{'form': form,'formset': formset})     
         

@login_required
def post_edit(request,slug):
    post = get_object_or_404(Post,slug=slug)
    form = forms.PostForm(instance=post)
    formset = forms.ImageInlineFormSet(queryset=form.instance.images_set.all())

    if request.user == post.author:
        if request.method == 'POST':
            form = forms.PostForm(request.POST,instance=post)
            formset = forms.ImageInlineFormSet(request.POST,request.FILES,queryset=form.instance.images_set.all())
            if form.is_valid() and formset.is_valid():
                form.save()
                image_updates = formset.save(commit=False)
                for image in image_updates:
                    image.article=post
                    image.save()
                for image in formset.deleted_objects:
                    image.delete()
                messages.success(request,"your post is edited.")
                return HttpResponseRedirect('/postfeeds')
    return render(request,'usersubmit/post_create.html',{'form':form,'formset':formset}) 


@login_required
def post_remove(request, slug):
   post = get_object_or_404(Post,slug=slug)
   if request.user == post.author:
       post.delete()
   return redirect('profiledetail', username=request.user.username)  
   
@ajax_required
@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                create_action(request.user, 'likes', post)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

       




    

usersubmit/templates/usersubmit/post_ajax.html
{% load thumbnail %}
{% load el_pagination_tags %}
{%  lazy_paginate 6  post %}
<div class="row">
  {% for article in post  %}
  <div class="col  s6 m4">
 <div class="card hoverable">

        <div class="card-image waves-effect waves-block waves-light">
<div class= "container ">
    {% thumbnail  article.get_first_image.image "300x300" crop="center" as im %}
                <a    href="{{ article.get_absolute_url }}"><img class="responsive-img" src="{{ im.url }}" ></a> 
                   {% endthumbnail %}
                    
</div>
                 
    </div>
    <div class="card-content">
      <span class=" activator grey-text text-darken-4">
        <div>
          
          <p>
          {% with total_likes=article.users_like.count users_like=article.users_like.all %}
          
           Likes:{{ total_likes }}
         
          {% endwith %}
          {% with total_images=article.images_set.all.count %}
        Slides:{{total_images}} 
          {% endwith %}
        <i activator class="material-icons  right">more_vert</i></span>
        </p>
        </div>
       
     
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
      <p>{{article.title}}</p>
    </div> 
    </div>
  </div>
           

          <!--comment-->
           
        

 
          {% endfor %}

</div>
{% show_more %}


 

usersubmit/templates/usersubmit/post_create.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Newly Post</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
</head>
<body>
  
<div class="container">
<div class="panel panel-success">
  <div class="panel-heading">Add your swify</div>
       <form id="post_form" method="post" action=""
      enctype="multipart/form-data">
      {% csrf_token %}
        <div class ="col-md-6">
        {{ form|crispy }} <br />
      
        </div>
       
       {{ formset.management_form }}
         <div class ="col-md-6">
    {% for form in formset %}
  <div class="formset">
     {{form|crispy }}
    {% endfor %}
    
    </div>
     <input type="submit" name="submit" value="Save" class="btn btn-primary" >
     </div>
    </form>   
    </div>
    </div>     
  

  <script>
    $('.formset').formset({
        addText: 'Add more',
        deleteText: 'Delete'
    });
</script> 

</body>
</html>

usersubmit/templates/usersubmit/post_detail.html
{% extends 'sub_nav.html' %}
{% load static from staticfiles %}



{% load thumbnail %}
{%  block title %}
      {{object.title}}
      {% endblock%}
{% block content %}
<div class="container ">
  <div class='row'>
  <div class="col s12 m9">
  <span class="card-title"><h5>{{ post.title|lower}}</h5></span>
   {% with total_images=post.images_set.all.count %}
      Slides:{{total_images}}
          {% endwith %}
  Story by <a href="{% url 'profiledetail' username=post.author %}">{{ post.author}}</a> {{post.created|timesince}}
   <!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58461a277584a19d"></script>

   <div  class="owl-carousel owl-theme">
                 {% for image in post.images_set.all %} 
                 <div class="row">
                 <div class="col s12  m9">
                   {% thumbnail  image.image "600x600"   as im %}
                 <img  class ='responsive-img' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                   {% endthumbnail %}
                 </div>
                 <div class="col s12 m3">
                   <div class="container ">
                     <p>{{image.body}}</p>
                   </div>
                    
                 </div>
                 </div>
                 {% endfor %}  
              </div>
  <hr>
 <div class="">
      {% with total_likes=post.users_like.count users_like=post.users_like.all %}
        <div class="image-info">
                <div>
                    <span class="count">
                        <span class="total">{{ total_likes }}</span>
                    </span>
                    <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like">

                        {% if request.user not in users_like %}
                             <i class=" material-icons red-text">bookmark_border</i>
                        {% else %}
                             <i class="material-icons red-text">bookmark</i>
                        {% endif %}
                    </a>
                     
                      {% if request.user == post.author %}
    <a class =" " href="{% url 'usersubmit:postedit' slug=post.slug %}"><i class="material-icons">settings</i></a>
    <a  class =" " href="{% url 'usersubmit:post_remove' slug=post.slug %}"><i class="material-icons">delete_forever</i></a>
{% endif %}  
                </div>
        </div>

        <div class="image-likes">
            {% for user in post.users_like.all %}
            {% thumbnail  user.profile.photo "20x20" crop="100%" as im %}
                <a href={% url 'profiledetail' username=user.username %} ><img class=" circle responsive-img" src="{{ im.url }}" ></a> 
                   {% endthumbnail %}
                <a href="{% url 'profiledetail' username=user.username %}">{{ user.username}}</a>,
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
          {% for tag in post.tags.all %}
          <a class ="indigo-text" href="tags/{{tag}}">#{{tag}}</a>
            <!--{% if not forloop.last %},{% endif %}-->
            {% endfor %}
          </div>
         
      
 
 <!--comment-->
 

</div>

         
<div class='col m3'>
<img class='responsive-img' src="https://cdn-images-1.medium.com/max/1600/1*ibN0ptxrg6LkZ5DZbKv2YA.png" alt="Burgerking add sponser">
</div>
</div>


          </div>
<hr>

{% endblock %}

 {% block script %} 
 <script>
   $('.owl-carousel').owlCarousel({
    items:1,
    loop:true,
    margin:10,
    autoHeight:true,
    nav:true,
});
 </script>

 <script type="text/javascript" src = "{% static 'el-pagination/js/el-pagination.js' %}"> </script>
     <script>$('#entries').endlessPaginate({paginateOnScroll: false, paginateOnScrollMargin: 200});</script>
   {% endblock %}

{% block domready %}
 $(document).ready(function(){
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "usersubmit:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.like').data('action');

                    // toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link html
                    $('a.like').html(previous_action == 'like' ? ' <i class="material-icons red-text">bookmark</i>' : ' <i class="material-icons red-text">bookmark_border</i>');

                    // update total likes
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
        });

    });
    	});



{% endblock %}


      $( document ).ready(function() {
    $("#comment-form").submit(function(event) {
event.preventDefault();
            var data= $(this).val();
            alert(data)
            $.ajax({
                data: $(this).serialize(),
                type:'POST',
                url:{% url 'usersubmit:create_post'  %} 
                success: function(data){
                    console.log(data);
                    $("#div1").html(data);
                    $(this).val('');
                },
                error: function(e){
                    console.log(e);
                }
            });
        });
});
 

usersubmit/templates/usersubmit/post_grid.html
{% extends "sub_nav.html" %}
{% load static from staticfiles %}

{% block title %}Post{% endblock %}

{% block content %}
 {{user.username}}
    <h1>All post:</h1>
    <div  id="entries"  class="endless_page_template">
      {% include page_template %}
    </div>
{% endblock %}

{% block js %}
       <script type="text/javascript" src = "{% static 'el-pagination/js/el-pagination.js' %}"> </script>
     <script>$('#entries').endlessPaginate({paginateOnScroll: true, paginateOnScrollMargin: 500});</script>
     

{% endblock %}

usersubmit/templates/usersubmit/post_list.html
{% extends 'app_base.html'%}
{% load thumbnail %}
{% block content %}

<div class="row">
  <div class="col s12 ">
    {% for article in post %}
  <div class="card-content">
       <span class="card-title"><h4>{{ article.title|upper}}</h4></span>
       <p>by {{ article.author|upper}}</p>
          <div>
              <div  class="owl-carousel owl-theme">
                 {% for image in article.images_set.all %} 
                 <div class="">
                   {% thumbnail  image.image "400x400" as im %}
                 <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                   {% endthumbnail %}
                     <p>{{image.body}}</p>
                 </div>
                 {% endfor %}  
              </div>
        </div>
           <hr>
 <div class="">
          {% for tag in article.tags.all %}
          <a href="tags/{{tag}}">#{{tag}}</a>
            <!--{% if not forloop.last %},{% endif %}-->
            {% endfor %}
          </div>
          <hr>
      {% if request.user == article.author %}
    <a href="{% url 'usersubmit:postedit' slug=article.slug %}">Edit</a>
    <a href="{% url 'usersubmit:post_remove' slug=article.slug %}">Delete</a>
{% endif %}   
          </div>
          {% endfor %}
{% endblock %} 
  </div>
</div>


            
         {% block script %} 
         <script>
         $('.owl-carousel').owlCarousel({
    items:1,
    margin:10,
    autoHeight:false,
    
});
     </script>
           {% endblock %}