accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='accounts/logged_out.html'), name='logout'),

    url(r'^password_change/$',
        PasswordChangeView.as_view(template_name='accounts/password_change_form.html'),
        name='password_change'),
    url(r'^password_change/done/$',
        PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'),

    url(r'^password_reset/$',
        PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
        name='password_reset'),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),  
     url(r'^users/follow/$', views.user_follow, name='user_follow'),
     url(r'^users/(?P<username>[-\w]+)/$', views.userdetail, name='profiledetail'),  
     url(r'^edit/$', views.edit, name='edit'),
     url(r'^dashboard/$', views.dashboard, name='dashboard'),     
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^$', views.homeview, name='home'),
    url(r'^feeds/$', views.ArticleListView.as_view(), name='feeds'),
    url(r'^feeds/category/version/$', views.VersionListView.as_view(), name='versionlist'),
     url(r'^feeds/category/tech/$', views.TechListView.as_view(), name='Techlist'),
      url(r'^feeds/category/review/$', views.ReviewListView.as_view(), name='Reviewlist'),
    url(r'^feeds/category/music&entertainment/$', views.MusicListView.as_view(), name='Musiclist'),
     url(r'^feeds/category/lifestyle/$', views.LifestyleListView.as_view(), name='Lifestylelist'),   
    url(r'^feeds/tags/(?P<tag>\w+)$',views.tagpage ,name='tagepage'),
    url(r'^archive/$', views.ArchiveView.as_view(), name="archive"),
    url(r'search/$', views.search,name = 'search'),
    url(r'^feeds/(?P<slug>\S+)$', views.ArticleDetailView.as_view(), name='detail'),
   
]

version/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls',)),
    url(r'^', include('blog.urls',  namespace='blog')),
    url(r'^', include('usersubmit.urls',  namespace='usersubmit')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    description=models.TextField(max_length=255,null=True)
    photo = ImageField(upload_to='users/%Y/%m/%d', blank=True)
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)
    

    def get_absolute_url(self):
        return reverse('profiledetail', kwargs={'username': self.username})



class Contact(models.Model):
    user_from = models.ForeignKey(User,related_name='rel_from_set')
    user_to = models.ForeignKey(User, related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


# Add following field to User dynamically
User.add_to_class('following',
                  models.ManyToManyField('self',
                                         through=Contact,
                                         related_name='followers',
                                         symmetrical=False))

                

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'The email already exist.Did you forget your password?')
        return email


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo','date_of_birth','description')
    

accounts/views.py
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.shortcuts import get_object_or_404, render, redirect

from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, UserEditForm,ProfileEditForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib import messages
from usersubmit.models import Post
from accounts.models import Contact
from el_pagination.decorators import page_templates
from common.decorators import ajax_required
from django.views.decorators.http import require_POST
from el_pagination.views import AjaxListView
from actions.models import Action
from actions.utils import create_action


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('accounts/acc_active_email.html', {
                'user':user, 
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your blog account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'accounts/verify.html',)
    
    else:
        form = SignupForm()
    
    return render(request, 'accounts/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, 'accounts/emailactivated.html',)
    else:
        return render(request, 'accounts/emailerror.html',)




@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Thats it!You have just updated your profile successfully!')
        else:
            messages.error(request, 'Error!Looks like you gave some inappropriate info.')
        return redirect('profiledetail', username=request.user.username) 
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'accounts/user/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})



@page_templates((
    ('usersubmit/post_ajax.html', None),
    ('accounts/user/follower.html', 'other_entries_page'),
    ('accounts/user/following.html', 'following'),
    )) 
def userdetail(
        request,username, template='accounts/user/detail.html', extra_context=None):
    context = {
        'user' : User.objects.get(username=username,is_active=True),
        'post':Post.objects.filter( author__username=username ),
        'followers':User.objects.get(username=username).followers.all(),
        'following':User.objects.get(username=username).following.all(),
       
    }
    if extra_context is not None:
        context.update(extra_context)
    return render(request,template, context)
'''

'''


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                              user_to=user)
                create_action(request.user, 'is following', user)                              
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ko'})
    return JsonResponse({'status':'ko'})



class FollowerListView(AjaxListView):
    context_object_name = "follower"
    template_name = "/post_grid.html"
    page_template='usersubmit/post_ajax.html'

    def get_queryset(self):
        return Post.objects.all()



@login_required
def dashboard(request):
    # Display all actions by default
    actions = Action.objects.all().exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        # If user is following others, retrieve only their actions
        actions = actions.filter(user_id__in=following_ids).select_related('user', 'user__profile').prefetch_related('target')
    actions = actions[:10]

    return render(request, 'accounts/dashboard.html', {'section': 'dashboard',
                                                      'actions': actions})

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/dashboard.html
{% extends "sub_nav.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    
  <div class='container'>
       <div class='row'>
          <h4>Activity Stream</h4>
    <div class='col m7' >
        
        {% for action in actions %}
            {% include "actions/action/detail.html" %}
        {% endfor %}
    </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/emailactivated.html
 {% extends "sub_nav.html" %} {% block content %}
<div class="container">
    <div class=' row card '>
        <!--grid2-->
        <div class='col m6'>

            <img class="responsive-img" src="https://cms-assets.tutsplus.com/uploads/users/1604/posts/28395/image/Flat-Summer06-step4.jpg"
                alt="">

        </div>

        <div class="col s12 m6  ">
            <div>
                <h5> Thanks for taking a time to verify your email. </h5>
                <br>
                <p>We do this to ensure spam and security purpose.Your email is verified.</p>
                <p>Start explorring ou lated feeds curated for you.</p>

            </div>

            <a href="{% url 'blog:feeds' %}">
                <h4>Explore now</h4>
            </a>
        </div>



    </div>


</div>

{% endblock %}

accounts/templates/accounts/emailerror.html
{% extends "sub_nav.html" %}

{% block content %}
<div class="container">
    <div class=' row card '>
  <!--grid2-->
    <div class = 'col m6'>

        <img class="responsive-img" src="https://cms-assets.tutsplus.com/uploads/users/1604/posts/28395/image/Flat-Summer06-step4.jpg" alt="">
        
    </div>

     <div class="col s12 m6  ">
       <div>
    <h5> Verification error. </h5>
    <br>
    <p> Sorry!we could not verify your email.Please register again with your valid email.</p>
   
    
</div>

        
</div>
   
  
  
</div>


</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "sub_nav.html" %}

{% block content %}
<div class="container">
    <div class=' row card '>
  <!--grid2-->
    <div class = 'col m6'>

        <img class="responsive-img" src="https://cms-assets.tutsplus.com/uploads/users/1604/posts/28395/image/Flat-Summer06-step4.jpg" alt="">
        
    </div>

     <div class="col s12 m6  ">
        <div class="container">
             <form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <div class ='center-align'>
        
             <input class ="btn light-blue accent-2" type="submit" value="login" />
        
         <a  class ="waves-effect waves-light btn teal accent-2" href="{% url "signup" %}">Create an Account </a>
    </div>
   <br />
   
    
</form> 
        </div>
        <div class= "center-align">
             <ul>
        <li><a class="chip  lime accent-2" href="#">Register an Account</a></li>
        <li> <a class="chip purple lighten-2"href="{% url 'password_reset'%}">Can't Remember Password?</a></li>
    </ul>
        </div>
        
</div>
   
  
  
</div>


</div>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "sub_nav.html" %}


{% block content %}
<p>Your password was changed.</p>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "sub_nav.html" %}}

{% block content %}

<form method="post">
    {% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

</div>
</form></div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "sub_nav.html" %}



{% block content %}

<p>Your password has been set.  You may go ahead and log in now.</p>

<p><a href="{{ login_url }}">'Log in </a></p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "sub_nav.html" %}
{% block content %}

{% if validlink %}

<p> "Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">'New password:'</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2"> 'Confirm password:'</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value='Change my password' />
</fieldset>
</form>

{% else %}

<p>"The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "sub_nav.html" %}

{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p> "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly."</p>

<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder."</p>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
"Please go to the following page and choose a new password:" 
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

accounts/templates/accounts/password_reset_form.html
{% extends "sub_nav.html" %}
{% block content %}

<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">'Email address:</label>
        {{ form.email }}
    </div>
    <input type="submit" value='Reset my password'  />
</fieldset>
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "sub_nav.html" %}
{% block content %}
<div class="container">
  <div class=" row card">
      <div class = 'col s12 m6'>

        <img class="responsive-img" src="https://cms-assets.tutsplus.com/uploads/users/1604/posts/28395/image/Flat-Summer06-step4.jpg" alt="">
        
    </div>
    <div class="col s12 m6 ">
      <div class="container">
         <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}
   <div class="center-align">
     <button class="waves-effect waves-light btn teal accent-2" type="submit">Sign up</button>
       <a class="waves-effect waves-light btn purple lighten-2" href="{% url 'login'%}"  >Already have an account?</a>
   </div>
  </form>
      </div>
    </div>
  </div>
</div>
 
{% endblock %}

accounts/templates/accounts/verify.html
{% extends "sub_nav.html" %}

{% block content %}
<div class="container">
    <div class=' row card '>
  <!--grid2-->
    <div class = 'col m6'>

        <img class="responsive-img" src="https://cms-assets.tutsplus.com/uploads/users/1604/posts/28395/image/Flat-Summer06-step4.jpg" alt="">
        
    </div>

     <div class="col s12 m6  ">
       <div>
    <h5> Email verification. </h5>
    <br>
    <p>We send an mail to your email.Please click the given link and verify your email.</p>
   
    
</div>

        
</div>
   
  
  
</div>


</div>

{% endblock %}