blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^$', views.homeview, name='home'),
    url(r'^feeds/$', views.ArticleListView.as_view(), name='feeds'),
    url(r'^feeds/category/version/$', views.VersionListView.as_view(), name='versionlist'),
     url(r'^feeds/category/tech/$', views.TechListView.as_view(), name='Techlist'),
      url(r'^feeds/category/review/$', views.ReviewListView.as_view(), name='Reviewlist'),
    url(r'^feeds/category/music&entertainment/$', views.MusicListView.as_view(), name='Musiclist'),
     url(r'^feeds/category/lifestyle/$', views.LifestyleListView.as_view(), name='Lifestylelist'),   
    url(r'^feeds/tags/(?P<tag>\w+)$',views.tagpage ,name='tagepage'),
    url(r'^archive/$', views.ArchiveView.as_view(), name="archive"),
    url(r'search/$', views.search,name = 'search'),
    url(r'^feeds/(?P<slug>\S+)$', views.ArticleDetailView.as_view(), name='detail'),
   
]

usersubmit/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'createpost/$', views.postview,name = 'createpost'),
     url(r'postfeeds/$', views.PostListView.as_view(),name = 'postfeeds'),
     url(r'^post_edit/(?P<slug>\S+)$', views.post_edit, name='postedit'),
     url(r'^remove/(?P<slug>\S+)/$', views.post_remove, name='post_remove'),
     url(r'^post/(?P<slug>\S+)$', views.ArticleDetailView.as_view(), name='postdetail'),
     url(r'^like/$', views.post_like, name='like'),
     
]

version/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls',)),
    url(r'^', include('blog.urls',  namespace='blog')),
    url(r'^', include('usersubmit.urls',  namespace='usersubmit')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app_base.html
  <!DOCTYPE html>
  {% load static from staticfiles %}
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <title>{% block title %}{% endblock %}</title>
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
      <!--owlplugin-->
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.theme.default.min.css' %}">

       <!--owlplugin-->
      <!--custom-->
       <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
<!--Navbar-->
<div class="row">

      <div class="container"><a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only"><i class="material-icons">menu</i></a></div>
      <ul id="nav-mobile" class="side-nav fixed" style="transform: translateX(0%);">
          <div class="search-wrapper card">
            <input id="search"><i class="material-icons">search</i>
            <div class="search-results"></div>
          </div>
        <li class="bold"><a href="about.html" class="waves-effect waves-teal">Profile</a></li>
        <li class="bold"><a href="getting-started.html" class="waves-effect waves-teal">Notificaions</a></li>
        <li class="no-padding">
        </li>
        <li class="bold"><a href="mobile.html" class="waves-effect waves-teal">Post</a></li>
        <li class="bold"><a href="showcase.html" class="waves-effect waves-teal">Settings</a></li>
        <li class="bold"><a href="themes.html" class="waves-effect waves-teal">Logout<span class="new badge"></span></a></li>
      </ul>

      <div class="col m4 hide-on-small-only">
    </div>
 <div class="col s12 m6">
      
        {% block content %}
   
   
   
   
   
   
   
   
   {% endblock %}
 


    </div>
    <div class ="col m2">
      
    </div>
</div>
    
  <!--Navbar End-->
  <!--slide bar-->
  
 
<!--footer-->
   <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Version
            <a class="grey-text text-lighten-4 right" href="#!">Learn More</a>
            </div>
          </div>
        </footer>
        <!--footer end-->
 <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
      <script type="text/javascript" src = "{% static 'js/custom.js' %}">
      </script>
       {% block script %}   {% endblock %}
    </body>
  </html>
        

templates/base_nav.html
  <!DOCTYPE html>
  {% load static from staticfiles %}
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/css?family=Overpass:600" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <title>{% block title %}{% endblock %}</title>
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
      <!--owlplugin-->
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.theme.default.min.css' %}">

       <!--owlplugin-->
      <!--custom-->
       <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
<!--Navbar-->
<div class="navbar-fixed">
 <nav class="nav-extended navcolor">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">  <img height="25px" width="25px"src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Dart-logo.png" alt="">Space</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">=</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="">Version</a></li>
        <li><a href="">News</a></li>
        <li><a href="">Reviews</a></li>
        <li><a href="">Tech</a></li>
        <li><a href="">Music</a></li>
        <li ><a class ="chip teal accent-3" href="{% url 'usersubmit:createpost' %}">Submit</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="">Version</a></li>
        <li><a href="">News</a></li>
        <li><a href="">Reviews</a></li>
        <li><a href="">Tech</a></li>
        <li><a href="">Music</a></li>
        <li><a class="chip teal accent-3" href="{% url 'usersubmit:createpost' %}">Lifestyle</a></li>
      </ul>
      </ul>
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab"><a class="active waves-effect"  href="#test1">Latest</a></li>
        <li class="tab"><a  class ="waves-effect"href="#test2 ">Popular</a></li>
        <li class="tab"><a class="waves-effect" href="#test3">Video</a></li>
       <li class =" left-align"> <div>
     <form action='{% url 'blog:search'%}' method="GET">
       <div class="input-field col s12">
          <input id="search" type="search" name='q'>
          <label for="search">Looking for something?</label>
        </div>
      </form>
   </div></li>
      </ul>
    </div>
  </nav>
  </div>

  <!--Navbar End-->
  <!--slide bar-->
   {% block content %}
   
   
   
   
   
   
   
   
   {% endblock %}
 
<!--footer-->
   <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Version
            <a class="grey-text text-lighten-4 right" href="#!">Learn More</a>
            </div>
          </div>
        </footer>
        <!--footer end-->
 <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
      <script type="text/javascript" src = "{% static 'js/custom.js' %}"></script>
   {% block script %}   {% endblock %}
      </script>
    </body>
  </html>
        

templates/sub_nav.html
<!DOCTYPE html>
{% load static from staticfiles %}

  <html>
    <head>
     <title> {%  block title %}

      {% endblock%}</title>
      <!--Import Google Icon Font-->
     <link href="https://fonts.googleapis.com/css?family=Overpass:600" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Rubik:500" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
       <link type="text/css" rel="stylesheet" href="{% static 'css/nprogress.css' %}"/>

      <!--custom-->
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'owlcarousel/assets/owl.theme.default.min.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">


      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
<!--Navbar-->
<div class="navbar-fixed">
 <nav class="nav-extended  navcolor">
    <div class="nav-wrapper container">
      <a href="{% url 'blog:home'%}" class="brand-logo "> <img src="https://www.shareicon.net/data/2015/10/07/113691_boat_512x512.png"  height= "40px" width="40px" alt=""> looper<span class="badge cyan accent-2">Beta</span></a>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">more_vert</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a href="{% url 'blog:versionlist' %}">Version</a></li>
        <li><a href="{% url 'blog:Techlist' %}">Tech</a></li>
        <li><a href="{% url 'blog:Reviewlist' %}">Reviews</a></li>
        <li><a href="{% url 'blog:Musiclist' %}">Music</a></li>
        <li><a href="{% url 'blog:Lifestylelist' %}">Culture</a></li>
        <li><a class="" href="{% url 'usersubmit:createpost' %}"><i class="material-icons light-blue-text">add_to_photos</i></a></li>
        <li> <a class ="dropdown-button accent-2" href="#" data-activates='dropdown2'> <i class="material-icons">more_vert</i></a></li>
       
  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    {% if user.is_authenticated %}
        <li class="chip"><a>@{{user.username}}</a> </li>
        <li><a href="{% url 'logout' %}">LogOut</a></li>
    {% else %}   
    <li><a href="{% url 'login' %}">SignIn</a></li>

    {% endif %}
    <li class="divider"></li>
    <li><a href="#!">Contact Us</a></li>
    <li><a href="#!">About Us</a></li>
    <li><a href="#!">Subscribe</a></li>
  </ul>
  <!--Dropdown-->
  <ul id='dropdown2' class='dropdown-content'>
    {% if user.is_authenticated %}
    
        <li><a href="{{ request.user.get_absolute_url  }}">{{request.user.username}}</a> </li>
       <li><a href="{% url 'logout' %}">LogOut</a></li>
    {% else %}   
    <li><a href="{% url 'login' %}">SignIn</a></li>

    {% endif %}
   
    <li class="divider"></li>
    <li><a href="#!">Contact Us</a></li>
    <li><a href="#!">About Us</a></li>
    <li><a href="#!">Subscribe</a></li>
  </ul>
        
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="{% url 'blog:versionlist' %}">Version</a></li>
       <li><a href="{% url 'blog:Techlist' %}">Tech</a></li>
        <li><a href="{% url 'blog:Reviewlist' %}">Reviews</a></li>
        <li><a href="{% url 'blog:Musiclist' %}">Music</a></li>
        <li><a href="{% url 'blog:Lifestylelist' %}">Lifestyle</a></li>
         <li> <a class ="dropdown-button accent-2" href="#" data-activates='dropdown1'>More</a></li>
      </ul>
      </ul>
    </div>
  </nav>
  </div>
  <div class="container customhide" >
     {% if messages %}
    {% for message in messages %}
    <div class=" card-panel green accent-2">
       <h6 class="center-align lime-text text-lighten-5">{{ message }} <i class="close  material-icons">highlight_off</i></h6>
      
    </div>
    {% endfor %}
{% endif %}
  </div>
  
 <div class=''>
   {% block content %}

  {% endblock %}
  
 </div>
 <footer class="page-footer newfooter">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="deep-purple-text brand-logo"><i class="brand-logo material-icons deep-purple-text">all_inclusive</i>lopper</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">For Brands</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Sign Up</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Sign In</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Contact</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Advertise with Looper</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 <i class="material-icons deep-purple-text">all_inclusive</i> looper
            <a class="grey-text text-lighten-4 right" href="#!">Feedback</a>
            </div>
          </div>
        </footer>
            

 <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
     <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
     <script type="text/javascript" src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
      <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js "></script>
       <script type="text/javascript" src = "{% static 'js/custom.js' %}"> </script>
        <script type="text/javascript" src = "{% static 'js/nprogress.js' %}"> </script>
        <script type="text/javascript">
NProgress.start();
NProgress.done();
</script>
       <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        
            {% block domready %}

            {% endblock %}
	
    </script>
       {% block script %}
    
       {% endblock %}
      </body>
  </html>
        